### PR TITLE
feature(versions): Adding Elgg version 2.1 to supported versions

### PR DESCRIPTION
**Pull request by iionly**

### CODE REVIEW

**Comment by juho-jaakkola** [comment]
Perhaps we should just rename `2.0` to `2`:
 - 2
 - 1.12
 - 1.11
 - etc.

**Comment by iionly** [comment]
I had already opened an issue about how to possibly reduce the number of version strings (https://github.com/Elgg/community_plugins/issues/126). It wasn't made a decision though and I lost interest.

The problem with putting all 2.X releases together in just 2 might no longer be that a plugin fails to work on later versions. Still, the could be deprecation warnings displayed within the page that can be quite annoying at least for site admins if not fixed by the plugin devs. Unfortunately, I don't think there's a way to fix deprecation issues in a BC manner even in the 2.X branch (e.g. autofeed deprecation issue in 2.1).

What I think might be a nice way to reduce the deprecation warning display annoyance for admins would be a developers plugin option to totally suppress these warnings to be displayed within a page (if that could be added to 2.1.X). That's something I also suggested once but it got somehow forgotten when a "dev mode/flag" was suggested instead (but this suggestion has been given up by now so it might make sense to reconsider my original idea).

But with a setting to suppress deprecation warnings I still don't know if putting all 2.X (or future 3.X etc.) into a single string as this sting also determines the versions you can search plugins for and some Elgg releases might introduce new features which a plugin might not be able to use in a BC manner so it would be necessary to indicate compatibility as 2.1 or 2.2 specifically.

**Comment by mrclay** [comment]
Deprecations are no longer displayed. Just logged as a warning.

**Comment by iionly** [comment]
Yeah, I figured that out just now, too. I thought it would be nice to be able to hide deprecation notices on screen (for development) while still get them written to the log. On a production site with logging off it's not relevant anyway but if I want to first deal with other more important issues than deprecation warnings during development the "pollution" of the output with the warnings can be annoying sometimes. I thought there would still be a distrinction being made between admins and normal users regarding who gets to see the deprecation warnings to allow for an additonal condition to be added here to be able to hide them from displayed but still getting logged but this seems not easily possible with the deprecation warnings being handled as normal warnings - blocking the warnings on screen would also block the addition to the log.

Anyway...  offtopic here. The point here is rather about putting Elgg minor releases together as the corresponding major release or not. It would surely reduce the list but as I mentioned before there's the issue with a new minor release possibly adding some new feature a plugin relies on, i.e. requiring a certain minor release as minimum.

**Comment by beck24** [comment]
I think we need the minor releases separately, there may be features for example in elgg 2.3 that a plugin relies on that don't exist in elgg 2.0.

**Pull request merged**
